"""data pairing

Revision ID: 3c82aa4e7fcb
Revises: ecd7259aa2b0
Create Date: 2024-11-18 11:12:05.698383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c82aa4e7fcb'
down_revision: Union[str, None] = 'ecd7259aa2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
