"""data pairing

Revision ID: 5e09ec3839a8
Revises: 3c82aa4e7fcb
Create Date: 2024-11-18 16:31:07.747150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e09ec3839a8'
down_revision: Union[str, None] = '3c82aa4e7fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budgetName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transaction', sa.Column('budgetID', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_budget_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'budget', ['budgetID'], ['id'])
    op.drop_column('transaction', 'budget_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_budget_id_fkey', 'transaction', 'budget', ['budget_id'], ['id'])
    op.drop_column('transaction', 'budgetID')
    op.drop_column('transaction', 'budgetName')
    # ### end Alembic commands ###
