"""data pairing

Revision ID: 605fa6dc0647
Revises: b96bb5538908
Create Date: 2024-11-03 15:54:08.656035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '605fa6dc0647'
down_revision: Union[str, None] = 'b96bb5538908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clerkUserId', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updatedAt')
    op.drop_column('user', 'createdAt')
    op.drop_column('user', 'imageUrl')
    op.drop_column('user', 'name')
    op.drop_column('user', 'clerkUserId')
    # ### end Alembic commands ###
