"""ditmemay

Revision ID: 7136417638be
Revises: 78793be90186
Create Date: 2024-11-11 16:43:18.449330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7136417638be'
down_revision: Union[str, None] = '78793be90186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
