"""data pairing

Revision ID: 78793be90186
Revises: f5206f3cbbd1
Create Date: 2024-11-10 19:19:33.206071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78793be90186'
down_revision: Union[str, None] = 'f5206f3cbbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('total_spent', sa.Integer(), nullable=False))
    op.add_column('budget', sa.Column('transaction', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'transaction')
    op.drop_column('budget', 'total_spent')
    # ### end Alembic commands ###
