"""data pairing

Revision ID: 99d160e1f2d5
Revises: 
Create Date: 2024-11-23 08:23:57.095924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d160e1f2d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.add_column('budget', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'budget', 'user', ['userId'], ['id'])
    op.drop_column('budget', 'transaction')
    op.add_column('transaction', sa.Column('budgetId', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_budgetID_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'budget', ['budgetId'], ['id'])
    op.drop_column('transaction', 'budgetName')
    op.drop_column('transaction', 'budgetID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budgetID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('budgetName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_budgetID_fkey', 'transaction', 'budget', ['budgetID'], ['id'])
    op.drop_column('transaction', 'budgetId')
    op.add_column('budget', sa.Column('transaction', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_column('budget', 'userId')
    op.create_table('wallet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wallet_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_pkey')
    )
    # ### end Alembic commands ###
