"""data pairing

Revision ID: b96bb5538908
Revises: a650aa63c0e7
Create Date: 2024-11-03 05:34:17.767574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96bb5538908'
down_revision: Union[str, None] = 'a650aa63c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budget_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'budget', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'budget_id')
    # ### end Alembic commands ###
