"""data pairing

Revision ID: f5206f3cbbd1
Revises: 059bb0b68f9d
Create Date: 2024-11-07 17:18:04.516187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5206f3cbbd1'
down_revision: Union[str, None] = '059bb0b68f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'user_id')
    # ### end Alembic commands ###
