"""data pairing

Revision ID: fcabc2b4b3e5
Revises: 
Create Date: 2024-11-20 16:49:54.746948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcabc2b4b3e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('transaction', sa.Integer(), nullable=False))
    op.alter_column('budget', 'totalSpent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('transaction', sa.Column('budgetName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transaction', sa.Column('budgetID', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_budget_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_user_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'budget', ['budgetID'], ['id'])
    op.drop_column('transaction', 'user_id')
    op.drop_column('transaction', 'budget_id')
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'user_id')
    op.add_column('transaction', sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_user_id_fkey', 'transaction', 'user', ['user_id'], ['id'])
    op.create_foreign_key('transaction_budget_id_fkey', 'transaction', 'budget', ['budget_id'], ['id'])
    op.drop_column('transaction', 'budgetID')
    op.drop_column('transaction', 'budgetName')
    op.alter_column('budget', 'totalSpent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('budget', 'transaction')
    # ### end Alembic commands ###
