import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Leftbar from '@/components/Leftbar'
import Rightbar from "@/components/Rightbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MoneyManager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Leftbar />
        <div className='ml-[300px] mr-[300px] p-4'>{children}</div>
        <Rightbar />
      </body>
    </html>
  );
}
